# Generated by Django 5.0.6 on 2024-06-29 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Wakhtane', '0004_alter_contact_unique_together_contact_user_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='user_contact',
        ),
    ]
