# Generated by Django 5.0.6 on 2024-07-01 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wakhtane', '0006_alter_contact_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
