# Generated by Django 5.0.6 on 2024-07-01 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Wakhtane', '0007_contact_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='email_verified',
        ),
    ]
