# Generated by Django 5.0.6 on 2024-07-01 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wakhtane', '0008_remove_contact_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='discussion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='Wakhtane.groupdiscussion'),
        ),
        migrations.AlterField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='Wakhtane.chat'),
        ),
    ]
